CREATE TABLE "api_keys" (
	"api_key" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"description" varchar(255),
	"expires_at" timestamp with time zone,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"is_active" boolean DEFAULT true NOT NULL,
	"user_id" integer,
	CONSTRAINT "api_keys_api_key_unique" UNIQUE("api_key")
);
--> statement-breakpoint
ALTER TABLE "line_users" DROP COLUMN "language";--> statement-breakpoint
DROP TYPE "public"."t_lang";